Repository team-yello/YELLO-iOS, pull requests merged in 2023-07, with the labels that each got.

#5 Chore [#4] adjust extension 추가
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Extensions/adjust+.swift
Labels: chore🧺, 채은🎐

#12 Feat [#10] TabBar 구현
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/Extensions/UITabBarController+.swift
  YELLO-iOS/YELLO-iOS/Global/Extensions/UIView+.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icFriendYelloSelected.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icFriendYelloSelected.imageset/friendyello.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icFriendYelloSelected.imageset/friendyello@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icFriendYelloSelected.imageset/friendyello@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icFriendYelloSelected.imageset/status=selected-3 1.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icFriendYelloSelected.imageset/status=selected-3 2.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icFriendYelloSelected.imageset/status=selected-3.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHomeSelected.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHomeSelected.imageset/home.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHomeSelected.imageset/home@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHomeSelected.imageset/home@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHomeSelected.imageset/status=selected-2 1.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHomeSelected.imageset/status=selected-2 2.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHomeSelected.imageset/status=selected-2.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icMyYelloSelected.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icMyYelloSelected.imageset/myyello.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icMyYelloSelected.imageset/myyello@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icMyYelloSelected.imageset/myyello@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icMyYelloSelected.imageset/status=selected-1 1.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icMyYelloSelected.imageset/status=selected-1 2.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icMyYelloSelected.imageset/status=selected-1.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPlusFriendSelected.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPlusFriendSelected.imageset/plusfriend.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPlusFriendSelected.imageset/plusfriend@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPlusFriendSelected.imageset/plusfriend@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPlusFriendSelected.imageset/status=selected-4 1.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPlusFriendSelected.imageset/status=selected-4 2.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPlusFriendSelected.imageset/status=selected-4.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icProfileSelected.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icProfileSelected.imageset/profile.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icProfileSelected.imageset/profile@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icProfileSelected.imageset/profile@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icProfileSelected.imageset/status=selected 1.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icProfileSelected.imageset/status=selected 2.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icProfileSelected.imageset/status=selected.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Font.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/AroundViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/MyYelloViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/RecommendingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarItem.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingViewController.swift
Labels: feat🪄, 희주🍀

#14 Feat [#13] 둘러보기 뷰 UI 및 Font, Color 수정
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Color.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Font.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/AroundView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/AroundViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
Labels: style🎨, 채은🎐

#17 Feat [#15] 추천친구 뷰 SegmentedControl 구현
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/KakaoFriendViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/RecommendingSegmentedControl.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/RecommendingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/SchoolFriendViewController.swift
Labels: feat🪄, style🎨, 채은🎐

#24 Feat [#21] 추천친구 뷰
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS.xcodeproj/xcshareddata/xcschemes/YELLO-iOS.xcscheme
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icAddFriendButton.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icAddFriendButton.imageset/btn.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icAddFriendButton.imageset/btn@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icAddFriendButton.imageset/btn@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icAddFriendButtonTapped.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icAddFriendButtonTapped.imageset/Frame 1171275618.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icAddFriendButtonTapped.imageset/Frame 1171275618@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icAddFriendButtonTapped.imageset/Frame 1171275618@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icRight.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icRight.imageset/chevron-right.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icRight.imageset/chevron-right@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icRight.imageset/chevron-right@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgBannerInvite.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgBannerInvite.imageset/Group 1171275622.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgBannerInvite.imageset/Group 1171275622@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgBannerInvite.imageset/Group 1171275622@3x.png
  YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Cells/FriendTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/FriendModel.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/KakaoFriendViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/SchoolFriendViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/EmptyFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/InviteBannerView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/KakaoFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/RecommendingSegmentedControl.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/SchoolFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/ViewController/KakaoFriendViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/ViewController/RecommendingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/ViewController/SchoolFriendViewController.swift
Labels: feat🪄, style🎨, 채은🎐

#27 Feat [#25] 내 프로필 뷰 UI 및 로직 구현
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/Extensions/UITableViewHeaderFooterView+.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnDelete.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnDelete.imageset/Frame 1171275636.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnDelete.imageset/Frame 1171275636@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnDelete.imageset/Frame 1171275636@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icArrowLeftWhite.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icArrowLeftWhite.imageset/arrow-left.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icArrowLeftWhite.imageset/arrow-left@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icArrowLeftWhite.imageset/arrow-left@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icArrowUp.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icArrowUp.imageset/arrow-up.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icArrowUp.imageset/arrow-up@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icArrowUp.imageset/arrow-up@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPlus.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPlus.imageset/plus.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPlus.imageset/plus@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPlus.imageset/plus@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgDefaultProfile.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgDefaultProfile.imageset/basic.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgDefaultProfile.imageset/basic@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgDefaultProfile.imageset/basic@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Font.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/CountCustomView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/FriendProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyFriendTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileHeaderView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/NavigationBarView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileCountView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/FriendProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/View/ProfileSettingView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/View/SettingCustomButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/View/SettingNavigationBarView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/ViewController/ProfileSettingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/WithdrawalAlertView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/WithdrawalCheckView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/WithdrawalCheckViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/WithdrawalView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/WithdrawalViewController.swift
  YELLO-iOS/YELLO-iOS/ViewController.swift
Labels: feat🪄, style🎨, 채은🎐

#31 Feat [#30] 옐로하기_메인 디테일 수정
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  YELLO-iOS/YELLO-iOS/Global/Extensions/UILabel+.swift
  YELLO-iOS/YELLO-iOS/Global/Extensions/UIView+.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress1.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress1.imageset/progress.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress1.imageset/progress@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress1.imageset/progress@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress10.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress10.imageset/progress-9.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress10.imageset/progress@2x-9.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress10.imageset/progress@3x-9.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress2.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress2.imageset/progress-1.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress2.imageset/progress@2x-1.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress2.imageset/progress@3x-1.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress3.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress3.imageset/progress-2.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress3.imageset/progress@2x-2.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress3.imageset/progress@3x-2.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress4.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress4.imageset/progress-3.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress4.imageset/progress@2x-3.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress4.imageset/progress@3x-3.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress5.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress5.imageset/progress-4.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress5.imageset/progress@2x-4.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress5.imageset/progress@3x-4.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress6.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress6.imageset/progress-5.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress6.imageset/progress@2x-5.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress6.imageset/progress@3x-5.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress7.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress7.imageset/progress-6.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress7.imageset/progress@2x-6.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress7.imageset/progress@3x-6.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress8.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress8.imageset/progress-7.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress8.imageset/progress@2x-7.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress8.imageset/progress@3x-7.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress9.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress9.imageset/progress-8.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress9.imageset/progress@2x-8.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgProgress9.imageset/progress@3x-8.png
  YELLO-iOS/YELLO-iOS/Presentation/Voting/BaseVotingETCView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/BackgroundColor.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/BaseVotingMainView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingDummy.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingLocked/VotingLockedViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStart.json
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
Labels: feat🪄, style🎨, 희주🍀

#39 Fix [#36] 옐로하기_시작 화면 이슈 해결
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingLocked/VotingLockedViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
Labels: fix⚙️, 희주🍀

#40 Fix [#37] TextField 포커싱
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/SearchBaseViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/OnboardingEndViewController.swift
Labels: fix⚙️, 지희🐰

#42 Style [#41] splash 구현 및 앱 아이콘 추가
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/172.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/196.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/216.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/48.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/55.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/64.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/66.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/88.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/92.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/SplashYelloFace.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/SplashYelloFace.imageset/SplashYelloFace.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/SplashYelloFace.imageset/SplashYelloFace@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/SplashYelloFace.imageset/SplashYelloFace@3x.png
  YELLO-iOS/YELLO-iOS/Info.plist
  YELLO-iOS/YELLO-iOS/Presentation/Splash/SplashTitleView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Splash/SplashViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Splash/splash.json
  YELLO-iOS/YELLO-iOS/Storyboard/Base.lproj/LaunchScreen.storyboard
Labels: style🎨, 지희🐰

#44 Fix [#38] 임시 QA 변동사항 적용
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Extensions/UITableView+.swift
  YELLO-iOS/YELLO-iOS/Global/Extensions/UIView+.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/DetailKeywordView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/DetailSenderView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/PointLackView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloNavigationBarView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Cells/SearchResultTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/AddFriendsViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/MyProfileFriendModel.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/FriendCountView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/FriendProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyFriendTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileHeaderView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/View/WithdrawalAlertView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/EmptyFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/InviteBannerView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/KakaoFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/NextButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/SchoolFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/ViewController/KakaoFriendViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
Labels: feat🪄, style🎨, fix⚙️, 채은🎐

#47 Feat [#46] 일러스트 추가
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgAround.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgAround.imageset/Frame 1171275648.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgAround.imageset/Frame 1171275648@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgAround.imageset/Frame 1171275648@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgMyYelloEmpty.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgMyYelloEmpty.imageset/Frame 1171275649.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgMyYelloEmpty.imageset/Frame 1171275649@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgMyYelloEmpty.imageset/Frame 1171275649@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgWithdrawalCheck.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgWithdrawalCheck.imageset/Frame 1171275645.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgWithdrawalCheck.imageset/Frame 1171275645@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgWithdrawalCheck.imageset/Frame 1171275645@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgWithdrawalFirst.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgWithdrawalFirst.imageset/Frame 1171275652.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgWithdrawalFirst.imageset/Frame 1171275652@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgWithdrawalFirst.imageset/Frame 1171275652@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgWithdrawalSecond.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgWithdrawalSecond.imageset/Frame 1171275653.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgWithdrawalSecond.imageset/Frame 1171275653@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgWithdrawalSecond.imageset/Frame 1171275653@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgWithdrawalThird.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgWithdrawalThird.imageset/Frame 1171275654.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgWithdrawalThird.imageset/Frame 1171275654@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgWithdrawalThird.imageset/Frame 1171275654@3x.png
  YELLO-iOS/YELLO-iOS/Presentation/Around/AroundView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloEmptyView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/View/WithdrawalCheckView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/View/WithdrawalView.swift
Labels: feat🪄, style🎨, 채은🎐

#51 Feat [#43] 결제 뷰 UI
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnFirstSubscribe.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnFirstSubscribe.imageset/btn_block.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnFirstSubscribe.imageset/btn_block@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnFirstSubscribe.imageset/btn_block@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnSecondSubscribe.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnSecondSubscribe.imageset/btn_block-1.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnSecondSubscribe.imageset/btn_block@2x-1.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnSecondSubscribe.imageset/btn_block@3x-1.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnSubscribe.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnSubscribe.imageset/Frame 1171275659.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnSubscribe.imageset/Frame 1171275659@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnSubscribe.imageset/Frame 1171275659@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnThirdSubscribe.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnThirdSubscribe.imageset/btn_block-2.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnThirdSubscribe.imageset/btn_block@2x-2.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnThirdSubscribe.imageset/btn_block@3x-2.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPaymentFirst.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPaymentFirst.imageset/Frame 1171275656.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPaymentFirst.imageset/Frame 1171275656@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPaymentFirst.imageset/Frame 1171275656@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPaymentSecond.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPaymentSecond.imageset/Frame 1171275657.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPaymentSecond.imageset/Frame 1171275657@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPaymentSecond.imageset/Frame 1171275657@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPaymentThird.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPaymentThird.imageset/Frame 1171275655.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPaymentThird.imageset/Frame 1171275655@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPaymentThird.imageset/Frame 1171275655@3x.png
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Payment/PaymentCollectionViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Payment/PaymentReadyViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Payment/PaymentView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Payment/PaymentViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/PaymentViewController.swift
Labels: feat🪄, style🎨, 채은🎐

#48 Feat [#35] TextField 아이디, 이름 유효성 검사 로직
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Extensions/String+.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/OnboardingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloGenderButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloHelperLabel.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloTextField.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloTextFieldView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/UserInfoView.swift
Labels: feat🪄, 지희🐰

#50 Style [#49] 일러스트 추가 및 카카오 로그인 뷰 구현
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/Extensions/UINavigationController+.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/OnboardingStart.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/OnboardingStart.imageset/온보딩_가입시작.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/OnboardingStart.imageset/온보딩_가입시작@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/OnboardingStart.imageset/온보딩_가입시작@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/addFriends.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/addFriends.imageset/Frame 1171275646.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/addFriends.imageset/Frame 1171275646@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/addFriends.imageset/Frame 1171275646@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icAlertCircle.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icAlertCircle.imageset/alert-circle.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icAlertCircle.imageset/alert-circle@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icAlertCircle.imageset/alert-circle@3x.png
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/OnboardingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoConnectViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/KakaoConnectView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/KakaoLoginView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/OnboardingEndView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/SignAnimation.json
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/onboarding_end.json
Labels: style🎨, 지희🐰

#53 Fix [#52] keyboard 이용 return
  YELLO-iOS/YELLO-iOS/Global/Extensions/UILabel+.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/SearchBaseViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/SchoolSearchViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/StudentInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/AddFriendsView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/EmptyFriendView.swift
Labels: feat🪄, 지희🐰

#54 Feat [#45] 일러스터 추가 및 타이머 디테일 수정
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPointAccumulate.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPointAccumulate.imageset/Frame 1171275647.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPointAccumulate.imageset/Frame 1171275647@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPointAccumulate.imageset/Frame 1171275647@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingLocked.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingLocked.imageset/Frame 1171275650.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingLocked.imageset/Frame 1171275650@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingLocked.imageset/Frame 1171275650@3x.png
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingLocked/VotingLockedViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
Labels: style🎨, chore🧺, 희주🍀

#56 Network [#55] 네트워크 BaseURL 등록 및 폴더링
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Info.plist
  YELLO-iOS/YELLO-iOS/Network/Base/APIEventLogger.swift
  YELLO-iOS/YELLO-iOS/Network/Base/APIRequestLoader.swift
  YELLO-iOS/YELLO-iOS/Network/Base/BaseResponse.swift
  YELLO-iOS/YELLO-iOS/Network/Base/Config.swift
  YELLO-iOS/YELLO-iOS/Network/Base/HTTPHeaderField.swift
  YELLO-iOS/YELLO-iOS/Network/Base/NetworkResult.swift
  YELLO-iOS/YELLO-iOS/Network/Base/NetworkService.swift
  YELLO-iOS/YELLO-iOS/Network/Base/TargetType.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Request/g.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Response/h.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/Router/MyYelloTarget.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/Service/MyYelloService.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/aa.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/b.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Service/OnboardingService.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/DTO/Request/i.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/DTO/Response/j.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/Router/ProfileTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/Service/ProfileService.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/DTO/Request/c.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/DTO/Response/d.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/Router/RecommendingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/Service/RecommendingService.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/DTO/Request/e.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/DTO/Response/f.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/Router/VotingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/Service/VotingService.swift
Labels: network🌐, 희주🍀

#59 Update .gitignore
  .gitignore
Labels: chore🧺, 지희🐰

#61 Network [#33] 카카오로그인 완료
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Info.plist
  YELLO-iOS/YELLO-iOS/Network/Base/Config.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
Labels: network🌐, 지희🐰

#63 Style [#60] 앱 아이콘, 스플래쉬 수정 완료
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/172.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/196.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/216.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/48.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/55.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/64.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/66.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/88.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/92.png
  YELLO-iOS/YELLO-iOS/Presentation/Splash/SplashTitleView.swift
Labels: style🎨, chore🧺, 지희🐰

#64 Network [#62] 추가 네트워크 세팅
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  YELLO-iOS/YELLO-iOS/Global/KeychainHandler.swift
  YELLO-iOS/YELLO-iOS/Network/Base/HTTPHeaderField.swift
Labels: chore🧺, network🌐, 채은🎐

#67 Chore [#66] 탭바 로직 수정
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Info.plist
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/TabBarHeight.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
Labels: feat🪄, chore🧺, 희주🍀

#69 Network[#57] 추천친구 API 연결
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Network/Base/BaseResponse.swift
  YELLO-iOS/YELLO-iOS/Network/Base/NetworkService.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/DTO/Request/RecommendingAddFriendRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/DTO/Request/RecommendingFriendRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/DTO/Request/RecommendingRequestQueryDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/DTO/Request/c.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/DTO/Response/RecommendingFriendResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/DTO/Response/d.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/Router/RecommendingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/Service/RecommendingService.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Cells/FriendsTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/AddFriendsView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Cells/FriendTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/FriendModel.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/KakaoFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/SchoolFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/ViewController/KakaoFriendViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/ViewController/SchoolFriendViewController.swift
Labels: network🌐, 채은🎐

#71 Network [#65] 카카오톡 연결
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Network/Base/APIRequestLoader.swift
  YELLO-iOS/YELLO-iOS/Network/Base/NetworkService.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/AddFriendsRequestQueryDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/KakaoLoginRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/MajorSearchRequestQueryDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/SchoolSearchRequestQueryDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/SignInRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/aa.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/CheckDuplicateResponeDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/KakaoLoginResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/MajorSearchResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/SchoolSearchResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/SignInResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/b.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Service/OnboardingService.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
Labels: network🌐, 지희🐰

#73 Network [#70] 내 프로필 API 붙이기
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Network/Base/NetworkService.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/DTO/Request/ProfileFriendRequestQueryDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/DTO/Request/i.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/DTO/Response/ProfileFriendResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/DTO/Response/ProfileUserResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/DTO/Response/j.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/Router/ProfileTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/Service/ProfileService.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/Service/RecommendingService.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/FriendProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyFriendTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/FriendProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Cells/FriendTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/TabbarHeight.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
Labels: network🌐, 채은🎐

#76 Network [#68] 옐로하기_메인 API 연결
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Network/Base/NetworkService.swift
  YELLO-iOS/YELLO-iOS/Network/Base/TargetType.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/DTO/Request/VotingAnswerListRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/DTO/Request/e.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/DTO/Response/VotingAnswerListResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/DTO/Response/VotingAvailableResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/DTO/Response/VotingListResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/DTO/Response/VotingSuffleResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/DTO/Response/f.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/Router/VotingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/Service/VotingService.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/BaseView/BaseVotingETCView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Enum/BackgroundColor.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingData.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
Labels: network🌐, 희주🍀

#75 Network [#72] 학교, 학과 검색 API 연결 및 무한 스크롤
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/IdValidRequestQueryDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/IdValidResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/MajorSearchResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/SchoolSearchResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Service/OnboardingService.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/SearchBaseViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/FindMajorViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/FindSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/SchoolSearchViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/StudentInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloTextField.swift
Labels: network🌐, 지희🐰

#80 Network [#77] 아이디 중복 체크 API 연결 및 로직 처리
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Color.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/KakaoLoginResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Payment/PaymentReadyViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Cells/FriendsTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/SearchBaseViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/FindMajorViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/FindSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/StudentInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/AddFriendsView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/ProfileViewController.swift
Labels: network🌐, 지희🐰

#81 Network [#78] 가입한 친구 불러오기 API 및 추천인 코드 유효성 판단
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/AddFriendsRequestQueryDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/JoinedFriendsRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/JoinedFriendsRequestQueryDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/SignUpRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/JoinedFriendsResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/SignUpResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Service/OnboardingService.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Cells/FriendsTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/User.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/AddFriendsViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/SchoolSearchViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/AddFriendsView.swift
Labels: network🌐, 지희🐰

#83 Feat [#79] 옐로하기 디테일 수정
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Extensions/UIView+.swift
  YELLO-iOS/YELLO-iOS/Network/Base/HTTPHeaderField.swift
  YELLO-iOS/YELLO-iOS/Network/Base/HTTPHeaderFieldKey.swift
  YELLO-iOS/YELLO-iOS/Network/Base/TargetType.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/Router/ProfileTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/Router/RecommendingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/DTO/Request/VotingAnswerListRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/Router/VotingTarget.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Enum/BackgroundColor.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VoteAnswerList.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingDummy.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
Labels: feat🪄, chore🧺, 희주🍀

#86 Network [#82] 회원가입 API 연결 추가
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/SignUpRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/KakaoLoginResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/SignUpResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Service/OnboardingService.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Cells/FriendsTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/User.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/AddFriendsViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/OnboardingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/FindMajorViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/FindSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/GenderViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoConnectViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/OnboardingEndViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/SchoolSearchViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/StudentIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/StudentInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/AddFriendsView.swift
Labels: network🌐, 지희🐰

#85 Feat [#84] 카카오톡 친구초대 구현
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
  YELLO-iOS/YELLO-iOS/Network/Base/HTTPHeaderFieldKey.swift
  YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/AddFriendsView.swift
Labels: feat🪄, 희주🍀

#90 Network [#87] 계정 탈퇴 API 연결, 로그아웃 구현
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/KeychainHandler.swift
  YELLO-iOS/YELLO-iOS/Network/Base/HTTPHeaderFieldKey.swift
  YELLO-iOS/YELLO-iOS/Network/Base/TargetType.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/DTO/Request/DeleteUserRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/Router/ProfileTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/Service/ProfileService.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/MyYelloDetailModel.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoConnectViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/View/ProfileSettingView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/ViewController/ProfileSettingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/View/WithdrawalAlertView.swift
Labels: feat🪄, network🌐, 지희🐰

#88 Network [#74] 내 옐로 API 연결 및 기타 변동 사항, 이슈 수정
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Network/Base/APIRequestLoader.swift
  YELLO-iOS/YELLO-iOS/Network/Base/NetworkService.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Request/MyYelloRequestQueryDTO.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Request/PayRequestBodyDTO.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Request/g.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Response/MyYelloDetailKeywordResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Response/MyYelloDetailNameResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Response/MyYelloDetailResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Response/MyYelloResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Response/PaymenyResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Response/h.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/Router/MyYelloTarget.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/Service/MyYelloService.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/DTO/Response/ProfileFriendResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/Router/ProfileTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/Service/ProfileService.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/DTO/Response/RecommendingFriendResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/Service/RecommendingService.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloDefaultTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloKeywordTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloNameTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/MyYelloDetailModel.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/DetailKeywordView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/GetHintView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailNavigationBarView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/PointLackView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/UsePointView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/MyYelloModel.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Payment/PaymentReadyViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Payment/PaymentViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloListView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Cells/FriendTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/FriendModel.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/KakaoFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/SchoolFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/ViewController/KakaoFriendViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/ViewController/SchoolFriendViewController.swift
Labels: fix⚙️, network🌐, 채은🎐

#92 Feat [#91] 친구 추가 API 연결 및 친구추가 로직 구현
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/SignUpRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/DTO/Request/DeleteUserRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Cells/FriendsTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/User.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/AddFriendsViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoConnectViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/OnboardingEndViewController.swift
Labels: feat🪄, network🌐, 지희🐰

#95 Network [#93] tokenrefresh API 연결 완료
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/KeychainHandler.swift
  YELLO-iOS/YELLO-iOS/Network/Base/APIRequestLoader.swift
  YELLO-iOS/YELLO-iOS/Network/Base/MyRequestInterceptor.swift
  YELLO-iOS/YELLO-iOS/Network/Base/TargetType.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/FindMajorViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/FindSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/OnboardingEndViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/View/WithdrawalAlertView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/KakaoFriendView.swift
Labels: network🌐, 지희🐰

#98 Chore [#96] TabBar 서버통신 로직 수정
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
Labels: fix⚙️, chore🧺, 희주🍀

#99 Fix [#97] 자동 로그인 구현
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/OnboardingEndViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/ViewController/ProfileSettingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/View/WithdrawalAlertView.swift
Labels: feat🪄, 지희🐰

#103 Fix [#102] 무한 스크롤 연속으로 되는 이슈 해결
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloListView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/KakaoFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/SchoolFriendView.swift
Labels: fix⚙️, 채은🎐

#105 Fix [#104] 친구 수 4명 이하 로직 수정
  YELLO-iOS/YELLO-iOS/Network/Base/APIRequestLoader.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingLocked/VotingLockedViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
Labels: fix⚙️, 희주🍀

#108 Feat [#106] 실제 링크 연결
  YELLO-iOS/YELLO-iOS/Network/Base/APIRequestLoader.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/FindMajorViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/FindSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/View/ProfileSettingView.swift
Labels: feat🪄, 채은🎐

#111 Fix [101] iOS 15 이하 기기 대응
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Presentation/Base/BaseBottomSheetViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/OnboardingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/SchoolSearchViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/StudentInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/StudentIdView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/BottomFriendProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
Labels: fix⚙️, 지희🐰

#110 Fix [#109] 포인트 레이아웃
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/GetHintView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailNavigationBarView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/PointLackView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/UsePointView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloNavigationBarView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/FriendCountView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
Labels: fix⚙️, 채은🎐

#112 Fix [#107] 글자길이에 맞게 이름,키워드 BackgroundView 대응
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
Labels: fix⚙️, 희주🍀

#113 Fix [#100] 내 옐로 스크롤 및 띄어쓰기 이슈
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloKeywordTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloNameTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloListView.swift
Labels: fix⚙️, 채은🎐

#116 Update README.md
  README.md
Labels: style🎨, 지희🐰

#115 Feat [#114] 인스타그램 공유 뷰 수정
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Font.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Font/Unbounded-Regular.ttf
  YELLO-iOS/YELLO-iOS/Info.plist
  YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
Labels: style🎨, 채은🎐

#118 Fix [#117] 토큰 재발급 로직 수정
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Network/Base/HTTPHeaderFieldKey.swift
  YELLO-iOS/YELLO-iOS/Network/Base/MyRequestInterceptor.swift
  YELLO-iOS/YELLO-iOS/Network/Base/TargetType.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/TokenRefreshResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Service/OnboardingService.swift
Labels: network🌐, 지희🐰

#123 Fix [#121] 2차 스프린트 전 수정사항 반영
  README.md
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingLocked/VotingLockedViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
Labels: fix⚙️, 희주🍀

#126 Fix [#124] 내 옐로 앱 터지는 이슈 해결
  YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Response/MyYelloResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloDefaultTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloKeywordTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloNameTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloListView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyFriendTableViewCell.swift
Labels: fix⚙️, 채은🎐

#128 Fix [#122] refresh token 로직 수정 완료
  YELLO-iOS/YELLO-iOS/Global/KeychainHandler.swift
  YELLO-iOS/YELLO-iOS/Network/Base/APIRequestLoader.swift
  YELLO-iOS/YELLO-iOS/Network/Base/MyRequestInterceptor.swift
  YELLO-iOS/YELLO-iOS/Network/Base/NetworkResult.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/TokenRefreshResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
Labels: feat🪄, fix⚙️, 지희🐰

#130 Feat [#125] SceneDelegate 설정 및 Loacl DB 구현
  YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/DTO/Response/VotingListResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Enum/BackgroundColor.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingData.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
Labels: feat🪄, fix⚙️, 희주🍀

#134 Fix [#133] 투표 중복으로 보내지는 이슈 해결
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
Labels: fix⚙️, 희주🍀

#136 Fix [#135] 카카오톡 친구 제한 해제
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoConnectViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/KakaoFriendView.swift
Labels: fix⚙️, 지희🐰

#132 [Fix] ID 글자수 제한
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift
Labels: fix⚙️, 지희🐰
