Repository team-yello/YELLO-iOS, pull requests merged in 2023-08, with the labels that each got.

#141 Feat [#137] 로컬 푸시 알림 구현
  YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
Labels: feat🪄, 희주🍀

#142 Feat [#127] 둘러보기 구현
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPolygon.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPolygon.imageset/Polygon 4.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPolygon.imageset/Polygon 4@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPolygon.imageset/Polygon 4@3x.png
  YELLO-iOS/YELLO-iOS/Presentation/Around/Cell/AroundTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/View/AroundEmptyView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/View/AroundView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/ViewController/AroundViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloKeywordTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloNameTableViewCell.swift
Labels: feat🪄, style🎨, 채은🎐

#149 Feat [#148] TabBar 수정사항 반영
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icFriendYelloSelected.imageset/friendyello.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icFriendYelloSelected.imageset/friendyello@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icFriendYelloSelected.imageset/friendyello@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHome.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHome.imageset/home.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHome.imageset/home@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHome.imageset/home@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHome.imageset/status=Default-1 1.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHome.imageset/status=Default-1 2.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHome.imageset/status=Default-1.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icMyYelloSelected.imageset/myyello.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icMyYelloSelected.imageset/myyello@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icMyYelloSelected.imageset/myyello@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPlusFriendSelected.imageset/plusfriend.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPlusFriendSelected.imageset/plusfriend@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icPlusFriendSelected.imageset/plusfriend@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icProfileSelected.imageset/profile.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icProfileSelected.imageset/profile@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icProfileSelected.imageset/profile@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Font.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarItem.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/BaseView/BaseVotingETCView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Enum/BackgroundColor.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/BaseVotingMainView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingLocked/VotingLockedViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
Labels: feat🪄, style🎨, fix⚙️, 희주🍀

#153 Network [#152] device token 발급 및 서버 전송
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/Shared/KeychainHandler.swift
  YELLO-iOS/YELLO-iOS/Global/Shared/User.swift
  YELLO-iOS/YELLO-iOS/Info.plist
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/KakaoLoginRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/SignUpRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/IdValidResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/OnboardingEndViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift
  YELLO-iOS/YELLO-iOS/YELLO-iOS.entitlements
Labels: network🌐, 지희🐰

#156 Feat [#139] 온보딩 수정 사항 반영
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Image.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icCheckCircleSelected.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icCheckCircleSelected.imageset/check-circle.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icCheckCircleSelected.imageset/check-circle@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icCheckCircleSelected.imageset/check-circle@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHighschool.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHighschool.imageset/icHighschool.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHighschool.imageset/icHighschool@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHighschool.imageset/icHighschool@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icUniv.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icUniv.imageset/icUniv.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icUniv.imageset/icUniv@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icUniv.imageset/icUniv@3x.png
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Constraints.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ProgressBarManager.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/AddFriendsViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/OnboardingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/SearchBaseViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/GenderViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoConnectViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindMajorViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/StudentIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/ProgressBarViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/PushSettingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/SchoolInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/SchoolSearchViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/SchoolSelectViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/StudentInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloGenderButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloNavigationBarView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloProgressBarView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloSelectButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloTextField.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/AddFriendsView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/GenderView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/HighSchoolView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/KakaoConnectView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/KakaoLoginView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/PushSettingView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/RecommendIdView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/SchoolSearchView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/SchoolSelectView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/StudentInfoView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/UniversityView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
Labels: style🎨, 지희🐰

#157 Feat [#154] 서버 푸시알림 구현
  YELLO-iOS/GoogleService-Info.plist
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/PointLackView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
Labels: feat🪄, 희주🍀

#163 Feat [#160] 2차 스프린트 온보딩 뷰 완성
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Extensions/UIWindow+.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Image.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHighSelected.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHighSelected.imageset/icHighSelected.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHighSelected.imageset/icHighSelected@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHighSelected.imageset/icHighSelected@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icUnivSelected.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icUnivSelected.imageset/icUnivSelected.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icUnivSelected.imageset/icUnivSelected@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icUnivSelected.imageset/icUnivSelected@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/idGuide.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/idGuide.imageset/idGuide.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/idGuide.imageset/idGuide@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/idGuide.imageset/idGuide@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/nameGuide.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/nameGuide.imageset/nameGuide.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/nameGuide.imageset/nameGuide@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/nameGuide.imageset/nameGuide@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/schoolGuide.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/schoolGuide.imageset/schoolGuide.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/schoolGuide.imageset/schoolGuide@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/schoolGuide.imageset/schoolGuide@3x.png
  YELLO-iOS/YELLO-iOS/Global/Shared/KeychainHandler.swift
  YELLO-iOS/YELLO-iOS/Presentation/Base/BaseBottomSheetViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ProgressBarManager.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/AddFriendsViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/OnboardingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/SearchBaseViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/GenderViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/HighSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindMajorViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/StudentIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/NameViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/OnboardingEndViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/PushSettingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/SchoolSelectViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UniversityViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloHelperLabel.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloNavigationBarView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloSelectButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloTextField.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloTextFieldView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/AddFriendsView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/GenderView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/HighSchoolView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/NameView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/RecommendIdView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/SchoolSelectView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/StudentIdView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/UniversityView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/UserInfoView.swift
Labels: feat🪄, style🎨, 지희🐰

#166 Feat [#164] TabBar 누르면 최상단으로 구현 & UI, 라이팅 수정 반영
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingLocked.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingLocked.imageset/Frame 1171275650.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingLocked.imageset/Frame 1171275650@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingLocked.imageset/Frame 1171275650@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingLocked.imageset/Frame 1171275788.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingLocked.imageset/Frame 1171275788@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingLocked.imageset/Frame 1171275788@3x.png
  YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/EmptyFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/InviteBannerView.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/BaseView/BaseVotingETCView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingLocked/VotingLockedViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
Labels: feat🪄, style🎨, 희주🍀

#172 Feat [#165] 푸시 설정 뷰 이동 로직 변경
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Extensions/UILabel+.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHeart.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHeart.imageset/icHeart.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHeart.imageset/icHeart@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icHeart.imageset/icHeart@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icSmallPoint.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icSmallPoint.imageset/icPoint.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icSmallPoint.imageset/icPoint@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icSmallPoint.imageset/icPoint@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/pushNotification.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/pushNotification.imageset/pushNotification.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/pushNotification.imageset/pushNotification@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/pushNotification.imageset/pushNotification@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/subscriptionPoint.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/subscriptionPoint.imageset/subscriptionPoint.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/subscriptionPoint.imageset/subscriptionPoint@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/subscriptionPoint.imageset/subscriptionPoint@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/subscriptionPointPlus.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/subscriptionPointPlus.imageset/subscriptionPointPlus.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/subscriptionPointPlus.imageset/subscriptionPointPlus@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/subscriptionPointPlus.imageset/subscriptionPointPlus@3x.png
  YELLO-iOS/YELLO-iOS/Global/Shared/User.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/KakaoLoginResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/PushSettingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/OnboardingEndView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/PushSettingView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/ViewController/ProfileSettingViewController.swift
Labels: feat🪄, network🌐, 지희🐰

#171 Feat [#169] 내 옐로 첫번째 쪽지 구현
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloNameTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloListView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/Cell/MyFriendSkeletonTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/Cell/MyFriendTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/SchoolFriendView.swift
Labels: feat🪄, 채은🎐

#176 Network [#174] 둘러보기 API 연결
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Network/Around/DTO/Request/AroundRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Around/DTO/Response/AroundResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Around/Router/AroundTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Around/Service/AroundService.swift
  YELLO-iOS/YELLO-iOS/Network/Base/NetworkService.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/Cell/AroundTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/View/AroundEmptyView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/View/AroundView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Cells/FriendTableViewCell.swift
Labels: network🌐, 채은🎐

#175 Feat [#167] 투표 시작화면 수정 UI 구현
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingStartBalloon1.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingStartBalloon1.imageset/Group 1171275842.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingStartBalloon1.imageset/Group 1171275842@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingStartBalloon1.imageset/Group 1171275842@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingStartBalloon2.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingStartBalloon2.imageset/Group 1171275843.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingStartBalloon2.imageset/Group 1171275843@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingStartBalloon2.imageset/Group 1171275843@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingStartBalloon3.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingStartBalloon3.imageset/Group 1171275844.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingStartBalloon3.imageset/Group 1171275844@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgVotingStartBalloon3.imageset/Group 1171275844@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Font.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/BaseView/BaseVotingETCView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStart.json
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
Labels: feat🪄, style🎨, 희주🍀

#181 Network [#177] 친구 검색 API 연결
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Network/Base/NetworkService.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/DTO/Response/RecommendingFriendResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Search/DTO/Request/FriendSearchRequestQueryDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Search/DTO/Response/FriendSearchResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Search/Router/SearchTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Search/Service/SearchService.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloDefaultTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloKeywordTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloOnlyNameTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/Cells/FriendSearchTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/View/FriendSearchView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/ViewController/FriendSearchViewController.swift
Labels: network🌐, 채은🎐

#179 Fix [#173] 온보딩 뷰 전체적인 로직 보수, 기기대응
  YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/Extensions/UIView+.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icKakao.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icKakao.imageset/ic_kakao.svg
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Cells/FriendsTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/AddFriendsViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/OnboardingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/SearchBaseViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/GenderViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoConnectViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindMajorViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/NameViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/OnboardingEndViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/PushSettingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/SchoolSelectViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UniversityViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/AddFriendsView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/KakaoConnectView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/KakaoLoginView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/OnboardingEndView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/PushSettingView.swift
Labels: feat🪄, fix⚙️, 지희🐰

#183 Feat [#180] 튜토리얼 뷰 구현
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Extensions/UIScreen+.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorial1.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorial1.imageset/tutorialLong1.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorial1.imageset/tutorialLong1@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorial1.imageset/tutorialLong1@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorial2.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorial2.imageset/tutorial2.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorial2.imageset/tutorial2@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorial2.imageset/tutorial2@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorial3.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorial3.imageset/tutorial3.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorial3.imageset/tutorial3@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorial3.imageset/tutorial3@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorial4.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorial4.imageset/tutorial4.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorial4.imageset/tutorial4@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorial4.imageset/tutorial4@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorialLong1.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorialLong1.imageset/tutorial1.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorialLong1.imageset/tutorial1@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorialLong1.imageset/tutorial1@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorialLong2.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorialLong2.imageset/tutorial2.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorialLong2.imageset/tutorial2@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorialLong2.imageset/tutorial2@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorialLong3.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorialLong3.imageset/tutorial3.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorialLong3.imageset/tutorial3@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorialLong3.imageset/tutorial3@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorialLong4.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorialLong4.imageset/tutorial4.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorialLong4.imageset/tutorial4@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/Tutorial/tutorialLong4.imageset/tutorial4@3x.png
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/PushSettingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/OnboardingEndView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Tutorial/View/FirstTutorialView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Tutorial/View/FourthTutorialView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Tutorial/View/SecondTutorialView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Tutorial/View/ThirdTutorialView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Tutorial/ViewController/TutorialViewController.swift
Labels: feat🪄, style🎨, 지희🐰

#184 Feat [#178] 안읽은 쪽지 개수 API 연결
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/DTO/Response/VotingUnreadResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/Router/VotingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/Service/VotingService.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/BaseView/BaseVotingETCView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
Labels: feat🪄, 희주🍀

#189 Feat [#185] 옐로하기 로티 애니메이션 추가
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/BaseVotingMainView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/Lottie/pagenation_1.json
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/Lottie/pagenation_2.json
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/Lottie/pagenation_3.json
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/Lottie/pagenation_4.json
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/Lottie/pagenation_5.json
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/Lottie/pagenation_6.json
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/Lottie/pagenation_7.json
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/Lottie/pagenation_8.json
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingDummy.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
Labels: feat🪄, style🎨, 희주🍀

#192 Feat [#188] Amplitude 연결
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
  YELLO-iOS/YELLO-iOS/Info.plist
  YELLO-iOS/YELLO-iOS/Network/Base/Config.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ProgressBarManager.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/OnboardingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoConnectViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/OnboardingEndViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/PushSettingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/ViewController/KakaoFriendViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Tutorial/ViewController/TutorialViewController.swift
Labels: feat🪄, 지희🐰

#191 Fix [#190] 내 옐로 수정사항 반영
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Button/MyYelloButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloListView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloView.swift
Labels: style🎨, fix⚙️, 채은🎐

#195 Fix [#193] 아이콘 뱃지 로직 수정
  YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
Labels: fix⚙️, 희주🍀

#199 Feat [#197] 2차 스프린트 수정된 세부 UI 적용
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgMultiplyByTwo.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgMultiplyByTwo.imageset/tag.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgMultiplyByTwo.imageset/tag@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgMultiplyByTwo.imageset/tag@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon1.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon1.imageset/order=1.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon1.imageset/order=1@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon1.imageset/order=1@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon2.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon2.imageset/order=2.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon2.imageset/order=2@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon2.imageset/order=2@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon3.imageset/order=3.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon3.imageset/order=3@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon3.imageset/order=3@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon4.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon4.imageset/order=4.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon4.imageset/order=4@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon4.imageset/order=4@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon5.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon5.imageset/order=5.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon5.imageset/order=5@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon5.imageset/order=5@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon6.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon6.imageset/order=6.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon6.imageset/order=6@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon6.imageset/order=6@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon7.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon7.imageset/order=7.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon7.imageset/order=7@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon7.imageset/order=7@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon8.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon8.imageset/order=8.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon8.imageset/order=8@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgYelloBalloon8.imageset/order=8@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Font.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/DTO/Response/VotingListResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/KakaoConnectView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/KakaoLoginView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/OnboardingEndView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/PushSettingView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/View/WithdrawalCheckView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/View/WithdrawalView.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/BaseView/BaseVotingETCView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingData.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingLocked/VotingLockedViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
Labels: style🎨, fix⚙️, 희주🍀

#198 Feat [#194] Event 및 UserProperty 연결 완료
  YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/Shared/User.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/View/AroundView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/ViewController/AroundViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/UsePointView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloListView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Cells/FriendsTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/AddFriendsViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/PushSettingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UniversityViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/FriendProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/View/ProfileSettingView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/ViewController/ProfileSettingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/View/WithdrawalAlertView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/View/WithdrawalCheckView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/View/WithdrawalView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/ViewController/FriendSearchViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/EmptyFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/InviteBannerView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/KakaoFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/SchoolFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/ViewController/RecommendingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/ViewController/SchoolFriendViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingLocked/VotingLockedViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
Labels: feat🪄, 지희🐰

#200 Fix [#196] 내 프로필 뷰 수정
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icProfileStar.imageset/Star 6.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icProfileStar.imageset/Star 6@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icProfileStar.imageset/Star 6@3x.png
  YELLO-iOS/YELLO-iOS/Presentation/Payment/View/PaymentNavigationBarView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileHeaderView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
Labels: style🎨, fix⚙️, 채은🎐

#204 Feat [#201] 추가된 푸시알림 구현 및 폴더링 수정
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Response/MyYelloDetailFullNameResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Response/MyYelloDetailResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/Router/MyYelloTarget.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/Service/MyYelloService.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/BaseVotingETCView/BaseVotingETCView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/NetworkEntity/VoteAnswerList.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/NetworkEntity/VotingData.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingDummy.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
Labels: feat🪄, network🌐, 희주🍀

#207 Feat [#205] 내 옐로 구독, 열람권 여부에 따른 UI 변경
  YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Response/MyYelloDetailResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Response/MyYelloResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Button/MyYelloButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloDefaultTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloKeywordTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloNameTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloOnlyNameTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/UseTicketView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloListView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/KakaoFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/SchoolFriendView.swift
Labels: feat🪄, style🎨, fix⚙️, 채은🎐

#211 Chore [#210] 개발 버전 설정
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS.xcodeproj/xcshareddata/xcschemes/YELLO_dev.xcscheme
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/100.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/102.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/1024.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/114.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/120.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/128.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/144.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/152.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/16.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/167.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/172.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/180.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/196.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/20.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/216.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/256.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/29.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/32.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/40.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/48.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/50.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/512.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/55.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/57.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/58.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/60.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/64.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/66.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/72.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/76.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/80.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/87.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/88.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/92.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/Contents.json
Labels: chore🧺, 지희🐰

#209 Network [#208] 옐로 플러스 구독 여부 UI 연결
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/DTO/Response/PurchaseInfoResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/Router/ProfileTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/Service/ProfileService.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
Labels: style🎨, network🌐, 채은🎐

#215 Feat [#212] 앱스토어 강제 업데이트 설정
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/Shared/AppStoreCheck.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloDefaultTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloKeywordTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloNameTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloOnlyNameTableViewCell.swift
Labels: feat🪄, 채은🎐

#218 Fix [#217] Amplitude 추가
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/PushSettingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
Labels: fix⚙️, 지희🐰

#219 Fix [#216] 내 옐로 오류 수정
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
Labels: fix⚙️, 채은🎐

#203 Network [#182] 인앱 결제 연결
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Network/Base/NetworkService.swift
  YELLO-iOS/YELLO-iOS/Network/Purchase/DTO/Request/PurchaseRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Purchase/DTO/Response/PurchaseResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Purchase/DTO/Response/PurchaseSubscibeNeedResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Purchase/Router/PurchaseTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Purchase/Service/IAPService.swift
  YELLO-iOS/YELLO-iOS/Network/Purchase/Service/MyProducts.swift
  YELLO-iOS/YELLO-iOS/Network/Purchase/Service/PurchaseService.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/UseTicketView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/View/PaymentPlusView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/View/ProfileSettingView.swift
Labels: style🎨, fix⚙️, network🌐, 채은🎐

#221 Fix [#220] 검색 재사용 이슈 해결
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/Cells/FriendSearchTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/View/FriendSearchView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/ViewController/FriendSearchViewController.swift
Labels: fix⚙️, 채은🎐

#224 Feat [#222] QA 사항 반영
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingLocked/VotingLockedViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
Labels: fix⚙️, 희주🍀

#226 Fix [#223] 2차 스프린트 전체 QA 수정 사항 반영
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/View/ProfileSettingView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/ViewController/ProfileSettingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/ViewController/FriendSearchViewController.swift
Labels: fix⚙️, 채은🎐

#229 Fix [#228] 서버 수정사항 및 디자인 QA 반영
  YELLO-iOS/YELLO-iOS/Network/Profile/Router/ProfileTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Purchase/Router/PurchaseTarget.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/ViewController/FriendSearchViewController.swift
Labels: fix⚙️, 채은🎐

#231 Fix [#230] 온보딩/디바이스 토큰 서버 변동 사항 적용
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/DeviceTokenRefreshRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/MajorSearchRequestQueryDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/SchoolSearchRequestQueryDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Service/OnboardingService.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindMajorViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindSchoolViewController.swift
Labels: fix⚙️, 지희🐰

#234 Feat [#233] 구독 연장 여부 뷰 구현
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnSubscriptionExtension.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnSubscriptionExtension.imageset/결제.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnSubscriptionExtension.imageset/결제@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnSubscriptionExtension.imageset/결제@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icExit.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icExit.imageset/exit.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icExit.imageset/exit@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icExit.imageset/exit@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgBenefit.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgBenefit.imageset/Group 1171275870.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgBenefit.imageset/Group 1171275870@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgBenefit.imageset/Group 1171275870@3x.png
  YELLO-iOS/YELLO-iOS/Presentation/Subscription/SubscriptionExtensionView.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
Labels: feat🪄, 희주🍀

#238 Fix [#236] 상점 로드 시점 수정
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
Labels: fix⚙️, 채은🎐

#240 Fix [#237] 외부 QA 반영
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
Labels: fix⚙️, 지희🐰

#239 Fix [#235] 외부 QA 사항 반영
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Tutorial/ViewController/TutorialViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
Labels: fix⚙️, 희주🍀
