Repository team-yello/YELLO-iOS, pull requests merged in 2023-09, with the labels that each got.

#244 Fix [#243] 상점 구독 여부 시점 수정
  YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
Labels: fix⚙️, 채은🎐

#247 Fix [#246] 친구 검색 QA 반영
  YELLO-iOS/YELLO-iOS/Network/Search/Router/SearchTarget.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/ViewController/FriendSearchViewController.swift
Labels: fix⚙️, 채은🎐

#250 Fix [#249] Amplitude QA 사항 반영
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/UsePointView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/UseTicketView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileHeaderView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
Labels: fix⚙️, 지희🐰

#251 Fix [#248] GoogleService API KEY 재발급
  .gitignore
  YELLO-iOS/GoogleService-Info.plist
  YELLO-iOS/YELLO-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  YELLO-iOS/YELLO-iOS/Global/Resources/Info.plist
  YELLO-iOS/YELLO-iOS/Info.plist
Labels: fix⚙️, 희주🍀

#254 Feat [#252] 4명 이하 투표 뷰 수정사항 반영
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/DTO/Response/VotingAvailableResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingLocked/VotingLockedViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
Labels: feat🪄, 희주🍀

#256 Fix [#253] 카카오싱크 로직 변경
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/OnboardingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UniversityViewController.swift
Labels: feat🪄, 지희🐰

#257 Feat [#253] 온보딩 고등학생 가입 기능 추가
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/102.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/AppIcon_dev.appiconset/Contents.json
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/HighSchoolClassRequestQueryDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/HighSchoolSearchRequestQueryDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/HighSchoolClassResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/HighSchoolSearchResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Service/OnboardingService.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ProgressBarManager.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/AddFriendsViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/GenderViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/HighSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoConnectViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/NameViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/SchoolSelectViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UniversityViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/GenderView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/NameView.swift
Labels: feat🪄, 지희🐰

#260 Fix [#258] 결제 중복 500 에러 해결
  YELLO-iOS/YELLO-iOS/Network/Purchase/Service/IAPService.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
Labels: fix⚙️, 채은🎐

#262 Fix [#261] 강제 업데이트 안되는 이슈 해결
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/Shared/AppStoreCheck.swift
Labels: fix⚙️, 채은🎐
