Repository team-yello/YELLO-iOS, pull requests merged in 2024-03, with the labels that each got.

#353 Fix [#352] 출시 이후 발견한 오류 해결
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/HighSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloSelectButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/View/PaymentView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/KakaoFriendView.swift
Labels: fix⚙️, 지희🐰

#357 Feat [#355] 프로필 변경 확인 팝업 및 수정 사항 적용
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/View/EditCheckView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/ViewController/EditSchoolInfoViewController.swift
Labels: feat🪄, 지희🐰

#358 Feat [#356] 건의사항 추가 반영
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/View/AroundView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Cells/FriendTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Components/FriendAddButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Model/FriendModel.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/Cells/FriendSearchTableViewCell.swift
Labels: feat🪄, fix⚙️, 채은🎐

#359 Feat [#354] 푸시알림 및 건의사항 반영 + 오류 수정
  YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/View/AroundView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/ViewController/AroundViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Notification/NotificationView.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
Labels: feat🪄, fix⚙️, 희주🍀

#361 Feat [#360] 3차 스프린트 건의사항 반영
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/View/AroundView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Notification/NotificationView.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
Labels: fix⚙️, 희주🍀

#366 Fix [#362] 3차 스프린트 5차 QA 수정사항 반영 및 앰플리튜드 반영
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  YELLO-iOS/YELLO-iOS/Presentation/Around/View/AroundView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/ViewController/AroundViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/ViewController/EditProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/ViewController/EditSchoolInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/EmptyFriendView.swift
Labels: feat🪄, fix⚙️, 채은🎐

#365 Feat [#364] 담당 뷰 앰플리튜드 적용
  YELLO-iOS/YELLO-iOS/Presentation/Event/ViewController/LunchEventViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Notification/NotificationView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Subscription/SubscriptionExtensionView.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
Labels: feat🪄, 희주🍀
