Repository team-yello/YELLO-iOS, pull requests merged in 2024-02, with the labels that each got.

#309 Chore [#308] 최소 버전 변경
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/HighSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UniversityViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/TabBarHeight.swift
Labels: chore🧺, 지희🐰

#305 Feat [#293] 프로필 수정 UI 구현
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/alert-circle.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/alert-circle.imageset/alert-circle.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/alert-circle.imageset/alert-circle@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/alert-circle.imageset/alert-circle@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/chevron-right-small.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/chevron-right-small.imageset/chevron-right-small.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/chevron-right-small.imageset/chevron-right-small@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/chevron-right-small.imageset/chevron-right-small@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/ic_Edit.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/ic_Edit.imageset/ic_Edit.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/ic_Edit.imageset/ic_Edit@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/ic_Edit.imageset/ic_Edit@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/rotate-ccw.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/rotate-ccw.imageset/rotate-ccw.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/rotate-ccw.imageset/rotate-ccw@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/rotate-ccw.imageset/rotate-ccw@3x.png
  YELLO-iOS/YELLO-iOS/Global/Shared/KeychainHandler.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/StudentIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloTextField.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/Cell/EditProfileTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/Cell/EditSchoolInfoTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/View/EditProfileHeaderView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/View/EditProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/View/EditSchoolInfoView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/ViewController/EditProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/ViewController/EditSchoolInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/InfoView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MainProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileHeaderView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/View/SettingNavigationBarView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/ViewController/ProfileSettingViewController.swift
Labels: feat🪄, 지희🐰

#313 Feat [#307] 타임라인 필터 구현
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icChevronDownGray.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icChevronDownGray.imageset/chevron_down_solid.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icChevronDownGray.imageset/chevron_down_solid@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icChevronDownGray.imageset/chevron_down_solid@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icInformation.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icInformation.imageset/alert-circle.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icInformation.imageset/alert-circle@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icInformation.imageset/alert-circle@3x.png
  YELLO-iOS/YELLO-iOS/Network/Around/DTO/Request/AroundRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Around/DTO/Response/AroundResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Around/Router/AroundTarget.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/Cell/TimeLineTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/View/AroundView.swift
Labels: feat🪄, network🌐, 채은🎐

#306 Feat [#289] 추천친구 프로필 바텀시트
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnAddFriend.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnAddFriend.imageset/Frame 1171275636.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnAddFriend.imageset/Frame 1171275636@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnAddFriend.imageset/Frame 1171275636@3x.png
  YELLO-iOS/YELLO-iOS/Network/Recommending/Router/RecommendingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/Service/RecommendingService.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Cells/FriendTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/KakaoFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/RecommendFriendProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/SchoolFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/ViewController/RecommendProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/ViewController/RecommendingViewController.swift
Labels: feat🪄, style🎨, network🌐, 채은🎐

#316 Fix [#310] 친구초대 팝업 UI 수정
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icKakaoShare.imageset/kakao_share.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icKakaoShare.imageset/kakao_share@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icKakaoShare.imageset/kakao_share@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icLinkCopy.imageset/link_copy.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icLinkCopy.imageset/link_copy@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icLinkCopy.imageset/link_copy@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Font.swift
  YELLO-iOS/YELLO-iOS/Network/Notification/Router/NotificationTarget.swift
  YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingView.swift
Labels: style🎨, fix⚙️, 희주🍀

#318 Feat [#314] 3차 스프린트 - 3순위 내 옐로 상단 배너
  YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icMegaphone.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icMegaphone.imageset/Megaphone.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icMegaphone.imageset/Megaphone@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icMegaphone.imageset/Megaphone@3x.png
  YELLO-iOS/YELLO-iOS/Network/Notification/Router/NotificationTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Notification/Service/NotificationService.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloNavigationBarView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
Labels: feat🪄, network🌐, 채은🎐

#317 Network [#315] 프로필 변경 API 연결 및 기능 구현
  YELLO-iOS/.swiftlint.yml
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS.xcodeproj/xcshareddata/xcschemes/YELLO_dev.xcscheme
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Shared/UserManager.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/DTO/Request/EditProfileRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/DTO/Response/ProfileUpadateDateResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/DTO/Response/ProfileUserResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/Router/ProfileTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/Service/ProfileService.swift
  YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/SearchBaseViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/HighSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindMajorViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/StudentIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UniversityViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/StudentIdView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/Cell/EditProfileTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/Cell/EditSchoolInfoTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/View/EditProfileHeaderView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/View/EditProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/View/EditSchoolInfoView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/ViewController/EditProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/ViewController/EditSchoolInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Helper/DateConverter.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/InfoView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MainProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileHeaderView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Model/MyProfileFriendModel.swift
Labels: feat🪄, network🌐, 지희🐰

#321 Feat [#320] 점심시간 이벤트 구현 완료
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgItemList.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgItemList.imageset/item_list.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgItemList.imageset/item_list@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgItemList.imageset/item_list@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPoint.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPoint.imageset/img.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPoint.imageset/img@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgPoint.imageset/img@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Font.swift
  YELLO-iOS/YELLO-iOS/Network/Base/HTTPHeaderFieldKey.swift
  YELLO-iOS/YELLO-iOS/Network/Base/NetworkService.swift
  YELLO-iOS/YELLO-iOS/Network/Base/TargetType.swift
  YELLO-iOS/YELLO-iOS/Network/Event/DTO/Request/EventRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Event/DTO/Response/EventResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Event/DTO/Response/EventRewardRsponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Event/Router/EventTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Event/Service/EventService.swift
  YELLO-iOS/YELLO-iOS/Presentation/Event/View/EventPointView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Event/View/LunchEventView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Event/ViewController/LunchEventViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Event/eventbox_default-4.json
  YELLO-iOS/YELLO-iOS/Presentation/Event/eventbox_open-4.json
  YELLO-iOS/YELLO-iOS/Presentation/Notification/NotificationView.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
Labels: feat🪄, style🎨, network🌐, 희주🍀

#322 Feat [#319] 프로필 공지 배너 구현
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/OnboardingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/View/EditProfileHeaderView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/InfoView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileHeaderView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
Labels: feat🪄, network🌐, 지희🐰

#331 Fix [#328] 3차 스프린트 - 1차 QA 변경 사항 적용
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Presentation/Around/View/AroundView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Base/BaseIconButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/Inviting/CloseButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailNavigationBarView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloNavigationBarView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/View/PaymentNavigationBarView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/InfoView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileHeaderView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/View/SettingNavigationBarView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/EmptyFriendView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/RecommendingNavigationBarView.swift
Labels: fix⚙️, 채은🎐

#329 Fix [#324] 학교/학과 검색 index 이슈 해결
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Global/Extensions/Array+.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/SearchBaseViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/HighSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindMajorViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/SchoolSelectViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UniversityViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/ViewController/EditSchoolInfoViewController.swift
Labels: fix⚙️, 지희🐰

#332 Fix [#327] 3차 스프린트 1차 QA 사항 반영
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgTicket.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgTicket.imageset/Frame 1171275818.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgTicket.imageset/Frame 1171275818@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/imgTicket.imageset/Frame 1171275818@3x.png
  YELLO-iOS/YELLO-iOS/Network/Base/APIRequestLoader.swift
  YELLO-iOS/YELLO-iOS/Network/Event/DTO/Response/EventResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Presentation/Event/View/EventPointView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Event/ViewController/LunchEventViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Notification/NotificationView.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
Labels: fix⚙️, 희주🍀

#333 Fix [#330] 3차 스프린트 QA 사항 반영
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Cells/FriendsTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/OnboardingViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UniversityViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloSelectButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloTextField.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloTextFieldView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/RecommendIdView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/ViewController/EditSchoolInfoViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/ViewController/WithdrawalCheckViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/ViewController/WithdrawalViewController.swift
Labels: fix⚙️, 지희🐰

#337 Feat [#334] 내 쪽지 전면 광고, 상점뷰, 투표 완료 시 리워드 광고 기능 개발
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
  YELLO-iOS/YELLO-iOS/Application/AppTracking.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Shared/UserManager.swift
  YELLO-iOS/YELLO-iOS/Network/Base/Config.swift
  YELLO-iOS/YELLO-iOS/Network/Base/NetworkService.swift
  YELLO-iOS/YELLO-iOS/Network/RewardAd/DTO/Request/RewardPossibleRequestQueryDTO.swift
  YELLO-iOS/YELLO-iOS/Network/RewardAd/DTO/Request/RewardRequestDTO.swift
  YELLO-iOS/YELLO-iOS/Network/RewardAd/DTO/Response/RewardPossibleResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/RewardAd/DTO/Response/RewardResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/RewardAd/Router/RewardTarget.swift
  YELLO-iOS/YELLO-iOS/Network/RewardAd/Service/RewardServices.swift
  YELLO-iOS/YELLO-iOS/Presentation/Event/View/EventPointView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/AdsTimer/Timer.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/Button/PointButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/View/NavigationBarCountView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/View/PaymentView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/Lottie/lottie_spinner_loading_profile.json
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
Labels: feat🪄, 지희🐰

#339 Fix [#338] 옐로하기 수정
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
Labels: fix⚙️, 희주🍀

#345 Fix [#343] 내 쪽지 레이아웃 깨지는 사항 수정
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
Labels: fix⚙️, 채은🎐

#346 Fix [#342] 3차 스프린트 3차 QA 사항 반영
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/Shared/UserManager.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Cells/FriendsTableViewCell.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/HighSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindSchoolViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/NameViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UniversityViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloTextField.swift
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/NameView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/AdsTimer/Timer.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/View/FriendSearchView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
Labels: fix⚙️, 지희🐰

#347 Fix [#344] 옐로하기 이슈 해결
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
Labels: fix⚙️, 희주🍀

#349 Fix [#348] 출시 전 qa 사항 수정
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/Button/PaymentNameKeyButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/Payment/Button/PointButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
Labels: fix⚙️, 지희🐰

#351 Fix [#350] 구독 정보 오류 해결
  YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
Labels: fix⚙️, 지희🐰
