Repository team-yello/YELLO-iOS, pull requests merged in 2024-01, with the labels that each got.

#295 Feat [#294] 인스타그램 공유하기 UI 수정사항 반영
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Color.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/Button/InstagramButton.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
Labels: style🎨, 채은🎐

#297 Feat [#292] 투표 애니메이션 추가 및 재구독뷰 서버 재연결
  YELLO-iOS/YELLO-iOS/Network/Purchase/DTO/Response/PurchaseSubscibeNeedResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Purchase/Router/PurchaseTarget.swift
  YELLO-iOS/YELLO-iOS/Presentation/Subscription/SubscriptionExtensionView.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
Labels: feat🪄, 희주🍀

#291 Style [#290] 건너뛰기 버튼 UI 변경
  YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/OnboardingViewController.swift
Labels: style🎨, 지희🐰

#300 Fix [#299] 버튼 중복 클릭 시 애니메이션으로 인한 오류 방지
  YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
Labels: fix⚙️, 희주🍀

#302 Feat [#298] 유저대상 공지 구현
  YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
  YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
  YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnCheckBox.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnCheckBox.imageset/box.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnCheckBox.imageset/box@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnCheckBox.imageset/box@3x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnNotCheckBox.imageset/Contents.json
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnNotCheckBox.imageset/box.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnNotCheckBox.imageset/box@2x.png
  YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/btnNotCheckBox.imageset/box@3x.png
  YELLO-iOS/YELLO-iOS/Network/Base/NetworkService.swift
  YELLO-iOS/YELLO-iOS/Network/Notification/DTO/Response/NotificationResponseDTO.swift
  YELLO-iOS/YELLO-iOS/Network/Notification/Router/NotificationTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Notification/Service/NotificationService.swift
  YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
  YELLO-iOS/YELLO-iOS/Presentation/Notification/NotificationView.swift
  YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
Labels: feat🪄, 희주🍀

#312 Chore [#311] v1 v2 분리
  YELLO-iOS/YELLO-iOS/Network/Around/Router/AroundTarget.swift
  YELLO-iOS/YELLO-iOS/Network/MyYello/Router/MyYelloTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Notification/Router/NotificationTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Profile/Router/ProfileTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Purchase/Router/PurchaseTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Recommending/Router/RecommendingTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Search/Router/SearchTarget.swift
  YELLO-iOS/YELLO-iOS/Network/Voting/Router/VotingTarget.swift
Labels: chore🧺
